'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/providers/convex-client-provider";
import { useEffect } from "react";
import { useUser } from "@clerk/nextjs"
import { redirect } from "next/navigation";
import { ClerkProvider } from "@clerk/nextjs";
import { AuthProvider } from "@/providers/authContext";
import { useAuthContext } from "@/providers/authContext";

const inter = Inter({ subsets: ["latin"] });

 const metadata: Metadata = {
  title: "SketchSync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const {checkAboutUser}=useAuthContext();
  // useEffect(()=>{
  //   checkAboutUser()

  // },[])



  return (
    <ConvexClientProvider> 
    <html lang="en">

      <body className={inter.className}>
        <AuthProvider>
       
          {children}
          </AuthProvider>

      </body>
     
    </html>
    </ConvexClientProvider> 
   
  );
}
